apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-demo
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: ./
    plugin:
      name: cmp-plugin-v1.0
      env:
        - name: FOO
          value: bar
    repoURL: https://github.com/erickbitso/cue-service-catalog
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
