apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      init:
        command: ["/bin/sh", "-c"]
        args: 
          - |
            git clone https://github.com/erickbitso/cue-service-catalog.git
      generate:
          command: [sh, -c]
          args:
            - |
              cd cue-service-catalog && cue cmd -t entity=$ARGOCD_ENV_SERVICE -t overrideFile=../deployments/$ARGOCD_ENV_SERVICE/deployment-config.yaml generate
