apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      init:
        command: [sh, -c, 'echo "Initializing..."', "ls -R"]
      generate:
          command: [sh, -c]
          args:
            - |
              cue cmd -t entity=models -t overrideFile=overrides/deployment-config.yaml generate
