apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-demo
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  sources:
    - repoURL: https://github.com/erickbitso/cue-service-catalog.git
      path: .
      targetRevision: HEAD
    - repoURL: https://github.com/erickbitso/service-repo.git
      path: .
      targetRevision: HEAD
      plugin:
        name: cmp-plugin-v1.0
        env:
          - name: SERVICE
            value: models
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
