apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
        - name: cue-plugin-setup
          image: busybox
          command:
            - sh
            - -c
            - |
              wget https://github.com/cue-lang/cue/releases/download/v0.9.2/cue_v0.9.2_linux_amd64.tar.gz -O - | tar xz && mv cue /tools/cue && chmod +x /tools/cue
          volumeMounts:
            - mountPath: /tools
              name: cue-plugin-tools
      containers:
        - name: cmp
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          image: alpine
          imagePullPolicy: IfNotPresent
          command: [/var/run/argocd/argocd-cmp-server]
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: cmp-plugin
            - mountPath: /tmp
              name: cmp-tmp
            - mountPath: /usr/local/bin
              name: cue-plugin-tools
      volumes:
        - name: cmp-plugin
          configMap:
            name: cmp-plugin
        - emptyDir: {}
          name: cmp-tmp
        - emptyDir: {}
          name: cue-plugin-tools
